# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/HW7/HW7

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/HW7/HW7

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/HW7/HW7/CMakeFiles /home/runner/work/HW7/HW7//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/HW7/HW7/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named bayan

# Build rule for target.
bayan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bayan
.PHONY : bayan

# fast build rule for target.
bayan/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bayan.dir/build.make CMakeFiles/bayan.dir/build
.PHONY : bayan/fast

CommandArgParser.o: CommandArgParser.cpp.o
.PHONY : CommandArgParser.o

# target to build an object file
CommandArgParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/CommandArgParser.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bayan.dir/build.make CMakeFiles/bayan.dir/CommandArgParser.cpp.o
.PHONY : CommandArgParser.cpp.o

CommandArgParser.i: CommandArgParser.cpp.i
.PHONY : CommandArgParser.i

# target to preprocess a source file
CommandArgParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/CommandArgParser.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bayan.dir/build.make CMakeFiles/bayan.dir/CommandArgParser.cpp.i
.PHONY : CommandArgParser.cpp.i

CommandArgParser.s: CommandArgParser.cpp.s
.PHONY : CommandArgParser.s

# target to generate assembly for a file
CommandArgParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/CommandArgParser.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bayan.dir/build.make CMakeFiles/bayan.dir/CommandArgParser.cpp.s
.PHONY : CommandArgParser.cpp.s

DirectoryContentFiltrator.o: DirectoryContentFiltrator.cpp.o
.PHONY : DirectoryContentFiltrator.o

# target to build an object file
DirectoryContentFiltrator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/DirectoryContentFiltrator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bayan.dir/build.make CMakeFiles/bayan.dir/DirectoryContentFiltrator.cpp.o
.PHONY : DirectoryContentFiltrator.cpp.o

DirectoryContentFiltrator.i: DirectoryContentFiltrator.cpp.i
.PHONY : DirectoryContentFiltrator.i

# target to preprocess a source file
DirectoryContentFiltrator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/DirectoryContentFiltrator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bayan.dir/build.make CMakeFiles/bayan.dir/DirectoryContentFiltrator.cpp.i
.PHONY : DirectoryContentFiltrator.cpp.i

DirectoryContentFiltrator.s: DirectoryContentFiltrator.cpp.s
.PHONY : DirectoryContentFiltrator.s

# target to generate assembly for a file
DirectoryContentFiltrator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/DirectoryContentFiltrator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bayan.dir/build.make CMakeFiles/bayan.dir/DirectoryContentFiltrator.cpp.s
.PHONY : DirectoryContentFiltrator.cpp.s

LazyFileGroupComparator.o: LazyFileGroupComparator.cpp.o
.PHONY : LazyFileGroupComparator.o

# target to build an object file
LazyFileGroupComparator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/LazyFileGroupComparator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bayan.dir/build.make CMakeFiles/bayan.dir/LazyFileGroupComparator.cpp.o
.PHONY : LazyFileGroupComparator.cpp.o

LazyFileGroupComparator.i: LazyFileGroupComparator.cpp.i
.PHONY : LazyFileGroupComparator.i

# target to preprocess a source file
LazyFileGroupComparator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/LazyFileGroupComparator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bayan.dir/build.make CMakeFiles/bayan.dir/LazyFileGroupComparator.cpp.i
.PHONY : LazyFileGroupComparator.cpp.i

LazyFileGroupComparator.s: LazyFileGroupComparator.cpp.s
.PHONY : LazyFileGroupComparator.s

# target to generate assembly for a file
LazyFileGroupComparator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/LazyFileGroupComparator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bayan.dir/build.make CMakeFiles/bayan.dir/LazyFileGroupComparator.cpp.s
.PHONY : LazyFileGroupComparator.cpp.s

MainManager.o: MainManager.cpp.o
.PHONY : MainManager.o

# target to build an object file
MainManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/MainManager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bayan.dir/build.make CMakeFiles/bayan.dir/MainManager.cpp.o
.PHONY : MainManager.cpp.o

MainManager.i: MainManager.cpp.i
.PHONY : MainManager.i

# target to preprocess a source file
MainManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/MainManager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bayan.dir/build.make CMakeFiles/bayan.dir/MainManager.cpp.i
.PHONY : MainManager.cpp.i

MainManager.s: MainManager.cpp.s
.PHONY : MainManager.s

# target to generate assembly for a file
MainManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/MainManager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bayan.dir/build.make CMakeFiles/bayan.dir/MainManager.cpp.s
.PHONY : MainManager.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bayan.dir/build.make CMakeFiles/bayan.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bayan.dir/build.make CMakeFiles/bayan.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bayan.dir/build.make CMakeFiles/bayan.dir/main.cpp.s
.PHONY : main.cpp.s

tests.o: tests.cpp.o
.PHONY : tests.o

# target to build an object file
tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests.cpp.o
.PHONY : tests.cpp.o

tests.i: tests.cpp.i
.PHONY : tests.i

# target to preprocess a source file
tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests.cpp.i
.PHONY : tests.cpp.i

tests.s: tests.cpp.s
.PHONY : tests.s

# target to generate assembly for a file
tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests.cpp.s
.PHONY : tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bayan"
	@echo "... test"
	@echo "... CommandArgParser.o"
	@echo "... CommandArgParser.i"
	@echo "... CommandArgParser.s"
	@echo "... DirectoryContentFiltrator.o"
	@echo "... DirectoryContentFiltrator.i"
	@echo "... DirectoryContentFiltrator.s"
	@echo "... LazyFileGroupComparator.o"
	@echo "... LazyFileGroupComparator.i"
	@echo "... LazyFileGroupComparator.s"
	@echo "... MainManager.o"
	@echo "... MainManager.i"
	@echo "... MainManager.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... tests.o"
	@echo "... tests.i"
	@echo "... tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

